---
sidebar: sidebar 
permalink: openshift/os-trident-element-iscsi.html 
summary:  
keywords: Trident, Element, Solidfire, iSCSI 
---
= NetApp Element iSCSI 配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要實現Trident與NetApp Element儲存系統的集成，您必須建立一個後端，以便使用 iSCSI 協定與儲存系統進行通訊。

. 下載的安裝檔案中提供了範例後端文件 `sample-input`資料夾層次結構。對於服務於 iSCSI 的NetApp Element系統，複製 `backend-solidfire.json`文件到您的工作目錄並編輯該文件。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/backends-samples/solidfire/backend-solidfire.json ./
[netapp-user@rhel7 trident-installer]$ vi ./backend-solidfire.json
----
+
.. 編輯使用者、密碼和 MVIP 值 `EndPoint`線。
.. 編輯 `SVIP`價值。
+
[listing]
----
 {
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://trident:password@172.21.224.150/json-rpc/8.0",
    "SVIP": "10.61.180.200:3260",
    "TenantName": "trident",
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
----


. 有了這個後端文件，運行以下命令來創建您的第一個後端。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend-solidfire.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| solidfire_10.61.180.200 | solidfire-san  | b90783ee-e0c9-49af-8d26-3ea87ce2efdf | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. 建立後端後，接下來必須建立儲存類別。與後端一樣，有一個範例儲存類別文件，可以根據 sample-inputs 資料夾中提供的環境進行編輯。將其複製到工作目錄並進行必要的編輯以反映已建立的後端。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[netapp-user@rhel7 trident-installer]$ vi storage-class-basic.yaml
----
. 對此文件唯一需要做的編輯是定義 `backendType`將值設定為新建立的後端的儲存驅動程式的名稱。還要注意名稱欄位值，該值必須在後續步驟中引用。
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "solidfire-san"
----
+

NOTE: 有一個可選字段稱為 `fsType`這是在這個文件中定義的。在 iSCSI 後端，可以將此值設定為特定的 Linux 檔案系統類型（XFS、ext4 等），或者可以刪除它以允許 OpenShift 決定使用哪種檔案系統。

. 運行 `oc`命令來建立儲存類別。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. 建立儲存類別後，您必須建立第一個持久化磁碟區宣告 (PVC)。有一個範例 `pvc-basic.yaml`也可用於執行位於 sample-inputs 中的此操作的檔案。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[netapp-user@rhel7 trident-installer]$ vi pvc-basic.yaml
----
. 對此文件唯一需要做的編輯是確保 `storageClassName`字段與剛剛建立的字段相符。  PVC 定義可以根據要設定的工作負載的需要進一步客製化。
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. 透過發出 `oc`命令。創建可能需要一些時間，具體取決於所創建的備份卷的大小，因此您可以在創建完成時觀察該過程。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[netapp-user@rhel7 trident-installer]$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-3445b5cc-df24-453d-a1e6-b484e874349d   1Gi        RWO            basic-csi      5s
----

